import {skillVocabulary} from './data/skills.js';

const DB_KEY='shiguang-local-v1';
const seedDB={profile:{name:'林溪'},conversations:[],cards:[],evidence:[]};
const db=(()=>{try{return {...seedDB,...JSON.parse(localStorage.getItem(DB_KEY)||'{}')}}catch{return structuredClone(seedDB)}})();
db.collected ||= [];
db.settings ||= {background:'mist',partner:'拾光',ip:'温柔倾听者',dailyCardTime:'21:30'};
if(typeof db.settings.cloudPinned!=='boolean')db.settings.cloudPinned=false;
db.profile={name:'林溪',phone:'',birthday:'',city:'上海',bio:'喜欢植物、整理和记录生活。',interests:'植物照护、社区分享、手作',...db.profile};
const saveDB=()=>localStorage.setItem(DB_KEY,JSON.stringify(db));
const state={loggedIn:false,profileSetup:false,sidebarCollapsed:false,authView:'login',loginMethod:'password',passwordVisible:false,codeSent:false,loginNotice:'',talkMode:'conversation',ipPanelOpen:true,cloudEmotion:'neutral',friendPhoto:null,activeConversation:null,tab:'talk',subpage:null,skillModal:null,sidebar:false,moodSheet:false,listening:false,cameraSheet:false,cameraEnabled:false,report:false,mood:'平静',partnerMessages:{},messages:[
  {role:'ai',text:'晚上好，林溪。今天有没有一件很小、但让你觉得“这是我做出来的”的事情？'},
  {role:'user',text:'我把阳台重新整理了一下，还给每盆植物做了标签。'},
  {role:'ai',text:'这不只是整理。你在观察植物的需要，也建立了一套自己的分类方法。你最满意哪个决定？'}
]};

const reports=[
 {date:'08.19',title:'让杂乱重新有秩序',tag:'空间整理',color:'#e96855'},
 {date:'08.12',title:'我其实很会照顾细节',tag:'观察力',color:'#7bcfc5'},
 {date:'08.03',title:'第一次把经验教给别人',tag:'表达能力',color:'#b29af2'}
];
const partners=[
 {name:'周宁',role:'内容运营',match:'92%',place:'上海 · 可线上',idea:'把你的植物经验变成易懂的系列内容',skills:['内容策划','用户表达','栏目运营'],opening:'你好，我看到了你关于植物照护和分类记录的能力线索。我很想和你一起试做一个「阳台植物新手手册」。'},
 {name:'阿禾',role:'社区组织',match:'86%',place:'上海 · 同城',idea:'一起发起小区阳台互助计划',skills:['社区连接','活动组织','资源协调'],opening:'你好，我正在组织一个社区阳台互助小组。你的观察和整理能力，可能正好能帮大家建立简单的养护档案。'},
 {name:'Mia',role:'摄影记录',match:'78%',place:'杭州 · 可线上',idea:'为养护过程建立有质感的视觉档案',skills:['视觉叙事','摄影记录','编辑设计'],opening:'你好，我很喜欢你把日常照护整理成方法的方式。想邀请你一起做一组植物成长的图文记录。'}
];
const reportItems=()=>[...db.cards.map(c=>({date:new Date(c.createdAt).toLocaleDateString('zh-CN',{month:'2-digit',day:'2-digit'}).replace('/','.'),title:c.title,tag:'新生成',color:'#c86f96',generated:true})),...reports];

const app=document.querySelector('#app');
async function apiRequest(path,{method='GET',body:payload}={}){const token=localStorage.getItem('shiguang-token')||'';const response=await fetch(path,{method,headers:{...(payload!==undefined?{'content-type':'application/json'}:{}),...(token?{authorization:`Bearer ${token}`}:{})},...(payload!==undefined?{body:JSON.stringify(payload)}:{})});const data=await response.json().catch(()=>({message:'服务返回格式不正确。'}));if(!response.ok)throw new Error(data.message||'请求失败，请稍后重试。');return data}
const apiJSON=(path,payload)=>apiRequest(path,{method:'POST',body:payload});
async function hydrateAccount(){const [{profile},conversationResult,cardResult,scheduleResult]=await Promise.all([apiRequest('/api/v1/me'),apiRequest('/api/v1/conversations'),apiRequest('/api/v1/cards'),apiRequest('/api/v1/settings/card-schedule')]);db.profile={...db.profile,...profile,interests:Array.isArray(profile.interests)?profile.interests.join('、'):profile.interests||''};db.conversations=conversationResult.conversations||[];db.cards=cardResult.cards||[];db.settings.dailyCardTime=scheduleResult.schedule?.localTime||'21:30';saveDB();return profile}
document.addEventListener('click',event=>{const method=event.target.closest('[data-login-method]');if(!method)return;state.loginMethod=method.dataset.loginMethod;state.loginNotice='';render()});
document.addEventListener('click',async event=>{const send=event.target.closest('[data-login-control="send-code"]');const submit=event.target.closest('[data-action="login"]');if(!send&&!submit)return;event.preventDefault();event.stopImmediatePropagation();const phone=document.querySelector('.login-form input[type="tel"]')?.value.trim()||'';const password=document.querySelector('.password-field input')?.value||'';const code=document.querySelector('.verify-field input')?.value.trim()||'';try{if(send){const result=await apiJSON('/api/v1/auth/code/request',{phone});state.codeSent=true;state.loginNotice=`${result.message}${result.devCode?` 验证码：${result.devCode}`:''}`;render();return}const path=state.authView==='register'?'/api/v1/auth/register':state.loginMethod==='code'?'/api/v1/auth/login/code':'/api/v1/auth/login/password';const result=await apiJSON(path,{phone,password,code});localStorage.setItem('shiguang-token',result.token);db.profile.phone=phone;const profile=await hydrateAccount();state.loggedIn=true;state.profileSetup=state.authView==='register'||!profile.onboardingComplete;state.loginNotice='';render()}catch(error){state.loginNotice=error.message||'暂时无法登录。';render()}},true);
document.addEventListener('keydown',async event=>{const input=event.target.closest('.composer textarea');if(!input||event.key!=='Enter'||event.shiftKey||!input.value.trim())return;event.preventDefault();event.stopImmediatePropagation();const text=input.value.trim();try{if(!state.activeConversation){const {conversation}=await apiJSON('/api/v1/conversations',{mood:state.mood});state.activeConversation=conversation.id;db.conversations.unshift(conversation)}state.messages.push({role:'user',text},{role:'ai',text:''});render();const response=await fetch(`/api/v1/conversations/${state.activeConversation}/messages`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${localStorage.getItem('shiguang-token')||''}`},body:JSON.stringify({content:text,mode:'normal'})});if(!response.ok){const data=await response.json().catch(()=>null);throw new Error(data?.message||'暂时无法连接时光。')}const reader=response.body?.getReader();if(!reader)throw new Error('没有收到模型回复。');const decoder=new TextDecoder();while(true){const {value,done}=await reader.read();if(done)break;state.messages[state.messages.length-1].text+=decoder.decode(value,{stream:true});render()}const current=db.conversations.find(x=>x.id===state.activeConversation);if(current&&current.title==='尚未命名的新对话')current.title=text.slice(0,24);saveDB()}catch(error){if(state.messages.at(-1)?.role==='ai')state.messages[state.messages.length-1].text=`暂时没有连接成功：${error.message}`;render()}},true);
document.addEventListener('click',event=>{if(event.target.closest('[data-open],[data-action="back"],[data-tab]'))requestAnimationFrame(()=>window.scrollTo({top:0,left:0,behavior:'instant'}))});
document.addEventListener('click',event=>{if(!event.target.closest('[data-action="back"]'))return;event.preventDefault();event.stopImmediatePropagation();state.subpage=state.subpage==='partners'?'opportunity':null;render()},true);
document.addEventListener('click',event=>{if(!event.target.closest('.friend-section-one .social-profile-card')||event.target.closest('button'))return;state.subpage='opportunity';render()});
document.addEventListener('click',event=>{const toy=event.target.closest('[data-cloud-toy]');if(toy){const moods=['happy','sad','cute'];state.cloudEmotion=moods[(moods.indexOf(state.cloudEmotion)+1)%moods.length];render();return}const emotion=event.target.closest('[data-cloud-emotion]');if(emotion){state.cloudEmotion=emotion.dataset.cloudEmotion;render();return}const control=event.target.closest('[data-cloud-action]');if(!control)return;state.ipPanelOpen=control.dataset.cloudAction==='open'||db.settings.cloudPinned;render()});
document.addEventListener('dblclick',event=>{if(!event.target.closest('.conversation-workspace')||event.target.closest('button,input,textarea'))return;state.ipPanelOpen=true;render()});
document.addEventListener('contextmenu',event=>{if(!event.target.closest('.cloud-ip-stage'))return;event.preventDefault();db.settings.cloudPinned=!db.settings.cloudPinned;state.ipPanelOpen=db.settings.cloudPinned||state.ipPanelOpen;saveDB();render()});
document.addEventListener('click',event=>{const view=event.target.closest('[data-auth-view]');if(view){state.authView=view.dataset.authView;state.loginNotice='';render();return}const action=event.target.closest('[data-login-control]');if(!action)return;if(action.dataset.loginControl==='password'){state.passwordVisible=!state.passwordVisible}else if(action.dataset.loginControl==='forgot'){state.loginNotice='验证码将发送到你的手机，用于重置密码。'}else if(action.dataset.loginControl==='send-code'){state.codeSent=true;state.loginNotice='验证码已发送，请注意查收。'}else if(action.dataset.loginControl==='qq'){state.loginNotice='正在连接 QQ 安全登录…'}else if(action.dataset.loginControl==='wechat'){state.loginNotice='正在连接微信安全登录…'}render()});
document.addEventListener('click',async event=>{if(!event.target.closest('[data-profile-save]'))return;const form=document.querySelector('.profile-settings-form');if(!form)return;const values=new FormData(form);try{const {profile}=await apiRequest('/api/v1/me',{method:'PATCH',body:{name:String(values.get('name')||''),birthday:String(values.get('birthday')||''),city:String(values.get('city')||''),bio:String(values.get('bio')||''),interests:String(values.get('interests')||'')}});db.profile={...db.profile,...profile,interests:(profile.interests||[]).join('、')};saveDB();state.subpage=null;state.tab='me';render()}catch(error){alert(error.message)}});
document.addEventListener('click',async event=>{if(!event.target.closest('[data-onboarding-save]'))return;const form=document.querySelector('.onboarding-form');if(!form)return;const values=new FormData(form);try{const {profile}=await apiJSON('/api/v1/me/onboarding',{name:String(values.get('name')||''),birthday:String(values.get('birthday')||''),city:String(values.get('city')||''),bio:String(values.get('bio')||'')});db.profile={...db.profile,...profile};saveDB();state.profileSetup=false;render()}catch(error){alert(error.message)}});
document.addEventListener('click',event=>{if(!event.target.closest('[data-action="login"]')||!state.loggedIn)return;state.profileSetup=true;render()});
document.addEventListener('click',event=>{if(!event.target.closest('[data-sidebar-collapse]'))return;state.sidebarCollapsed=!state.sidebarCollapsed;render()});
document.addEventListener('click',event=>{const open=event.target.closest('[data-skill-modal]');const close=event.target.closest('.skill-modal-close')||event.target.matches('.skill-modal-layer');if(!open&&!close)return;event.preventDefault();event.stopImmediatePropagation();state.skillModal=open?Number(open.dataset.skillModal):null;render()},true);
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&state.skillModal!==null){state.skillModal=null;render()}});
document.addEventListener('click',async event=>{const button=event.target.closest('[data-action="new-chat"]');if(!button)return;event.preventDefault();event.stopImmediatePropagation();try{const {conversation}=await apiJSON('/api/v1/conversations',{mood:state.mood});db.conversations.unshift(conversation);state.sidebar=false;state.activeConversation=conversation.id;state.messages=[{role:'ai',text:'新的对话已经准备好了。今天你想先说哪一件事？'}];state.tab='talk';render()}catch(error){alert(error.message)}},true);
document.addEventListener('click',async event=>{const button=event.target.closest('[data-chat]');if(!button)return;event.preventDefault();event.stopImmediatePropagation();try{const {conversation,messages}=await apiRequest(`/api/v1/conversations/${button.dataset.chat}`);state.sidebar=false;state.activeConversation=conversation.id;state.messages=messages.length?messages.map(m=>({role:m.role==='assistant'?'ai':'user',text:m.content})):[{role:'ai',text:'这段对话还没有内容。你想从哪里继续？'}];state.mood=conversation.mood||'平静';state.tab='talk';render()}catch(error){alert(error.message)}},true);
document.addEventListener('change',event=>{const setting=event.target.closest('[data-setting="dailyCardTime"]');if(!setting)return;db.settings.dailyCardTime=setting.value;saveDB();apiRequest('/api/v1/settings/card-schedule',{method:'PUT',body:{enabled:true,localTime:setting.value,timezone:'Asia/Shanghai'}}).catch(error=>alert(error.message))},true);
let cloudPullStart=null;
document.addEventListener('pointerdown',event=>{if(event.target.closest('.cloud-pull-handle'))cloudPullStart=event.clientY});
document.addEventListener('pointerup',event=>{if(cloudPullStart!==null&&event.clientY-cloudPullStart>18){state.ipPanelOpen=true;render()}cloudPullStart=null});
function render(){if(!state.loggedIn){app.innerHTML=loginPage();bind();return}if(state.profileSetup){app.innerHTML=onboardingPage();bind();return}ensureDailyCard();const content=state.subpage?detailPage(state.subpage):`<section class="page ${state.tab==='talk'?'active':''}" id="talk">${talkPage()}</section><section class="page ${state.tab==='friend'?'active':''}" id="friend">${friendPage()}</section><section class="page ${state.tab==='report'?'active':''}" id="report">${reportPage()}</section><section class="page ${state.tab==='me'?'active':''}" id="me">${mePage()}</section>`;app.innerHTML=`<main class="phone-shell workspace-shell ${state.sidebarCollapsed?'sidebar-collapsed':''} ${state.subpage?'has-subpage':''} tab-${state.tab} mood-theme-${state.mood}">
  ${workspaceSidebar()}<div class="workspace-main">
  <header class="app-head"><button class="menu-trigger" data-action="${state.subpage?'back':'sidebar'}" aria-label="${state.subpage?'返回上一页':'打开对话记录'}">${state.subpage?'<i>←</i><span>返回</span>':'☰'}</button><div class="brand"><i>拾</i><div><b>${state.subpage?'个人空间':'我是谁'}</b><span>${state.subpage?'PRIVATE WORKSPACE':'BLUE ARCHIVE · PERSONAL FIELD'}</span></div></div><button class="privacy" data-action="open-privacy">隐私中心</button></header>
  ${content}
  </div>${state.sidebar?sidebar():''}${state.moodSheet?moodSheet():''}${state.cameraSheet?cameraSheet():''}${state.report?reportSheet():''}${state.skillModal!==null?skillModal(state.skillModal):''}
 </main>`;bind()}

function loginPage(){const register=state.authView==='register';const codeMode=!register&&state.loginMethod==='code';return `<main class="login-screen formal-login"><div class="login-tide" aria-hidden="true"><i></i><i></i><i></i></div><section><div class="login-brand-row"><div class="login-mark">拾</div><div><b>拾光</b><span>PRIVATE GROWTH ARCHIVE</span></div></div><header><span>${register?'创建账户':'欢迎回来'}</span><h1>${register?'注册你的拾光账户':'登录你的个人成长空间'}</h1><p>${register?'创建账号并设置密码，开始保存属于你的故事。':'继续记录故事、整理能力线索，并与同路人保持联系。'}</p></header>${register?'':`<div class="login-method-tabs"><button class="${state.loginMethod==='password'?'on':''}" data-login-method="password">账号密码</button><button class="${state.loginMethod==='code'?'on':''}" data-login-method="code">账号验证码</button></div>`}<div class="login-form"><label><span>手机号账号</span><input type="tel" placeholder="请输入手机号账号" autocomplete="tel" /></label>${register||codeMode?`<label class="verify-field"><span>账号验证码</span><input type="text" inputmode="numeric" maxlength="6" placeholder="请输入 6 位验证码"/><button type="button" data-login-control="send-code">${state.codeSent?'重新生成':'获取验证码'}</button></label>`:''}${register||!codeMode?`<label class="password-field"><span>${register?'设置密码':'账号密码'}</span><input type="${state.passwordVisible?'text':'password'}" placeholder="${register?'设置 8 位以上密码':'请输入账号密码'}" autocomplete="${register?'new-password':'current-password'}"/><button type="button" data-login-control="password">${state.passwordVisible?'隐藏':'显示'}</button></label>`:''}${register?'':`<div class="login-options"><label><input type="checkbox" checked/><span>记住登录</span></label>${codeMode?'<span>验证码仅显示在当前页面</span>':'<button data-login-control="forgot">忘记密码？</button>'}</div>`}${state.loginNotice?`<p class="login-notice">${state.loginNotice}</p>`:''}<button class="login-submit" data-action="login"><span>${register?'注册并进入拾光':'登录并进入拾光'}</span><b>↗</b></button><div class="register-row"><span>${register?'已经有账户？':'还没有账户？'}</span><button data-auth-view="${register?'login':'register'}">${register?'返回登录':'创建新账户'}</button></div></div><small class="login-legal">初版验证码由页面生成，不发送短信。你的对话、照片和成长记录默认仅自己可见。</small></section></main>`}
function onboardingPage(){return `<main class="onboarding-screen"><section><div class="onboarding-progress"><i></i><span>完成个人信息 · 1 / 1</span></div><header><div class="login-mark">拾</div><span>WELCOME TO SHIGUANG</span><h1>先让我们认识你。</h1><p>这些信息用于生成更贴近你的成长记录，也可以之后在“个人信息”中修改。</p></header><form class="onboarding-form"><div class="onboarding-grid"><label><span>你的名字</span><input name="name" value="${db.profile.name}" placeholder="怎么称呼你？"/></label><label><span>生日</span><input name="birthday" type="date" value="${db.profile.birthday}"/></label><label><span>所在城市</span><input name="city" value="${db.profile.city}" placeholder="例如：上海"/></label><label class="wide"><span>简单介绍一下自己</span><textarea name="bio" rows="4" placeholder="你喜欢什么？最近在关注什么？">${db.profile.bio}</textarea></label></div><button type="button" data-onboarding-save><span>保存并开始我的故事</span><b>↗</b></button></form><small>你的生日和个人资料默认仅自己可见。</small></section></main>`}
function talkPage(){return `<div class="conversation-workspace ${state.ipPanelOpen?'ip-open':'ip-folded'} cloud-${state.cloudEmotion} ${db.settings.cloudPinned?'cloud-pinned':''}"><button class="cloud-pull-handle" data-cloud-action="open" aria-label="唤起云朵"><i>⌄</i></button><section class="talk-flow"><div class="ocean-motion" aria-hidden="true"><i></i><i></i><i></i><span></span></div><section class="cloud-ip-stage"><div class="cloud-scene" data-cloud-toy role="button" tabindex="0" aria-label="云朵玩偶，单击切换动作，右键设置常驻"><i class="cloud cloud-one"><span class="cloud-face"><b></b><b></b><em></em></span><span class="cloud-arm arm-left"></span><span class="cloud-arm arm-right"></span><span class="cloud-stitch"></span></i><i class="cloud-shadow"></i><span class="cloud-spark s1">✦</span><span class="cloud-spark s2">·</span></div></section><section class="conversation">${state.messages.map((m,i)=>`<article class="bubble ${m.role}">${m.role==='ai'?'<span>时光</span>':''}<p>${m.text||'<span class="thinking"><i></i><i></i><i></i></span>'}</p>${i===state.messages.length-1&&m.role==='ai'?'<small>你可以慢慢想，我在听。</small>':''}</article>`).join('')}</section>
 <section class="input-dock"><div class="signals"><button data-action="camera" class="${state.cameraEnabled?'on':''}"><i>⌾</i><span>表情辅助</span><small>${state.cameraEnabled?'已开启':'由你决定'}</small></button><div><b>情绪信号</b><span>${state.mood} · 低强度</span></div></div><div class="composer"><button class="plus">＋</button><textarea placeholder="输入你的想法…" rows="1"></textarea><button class="voice ${state.listening?'live':''}" data-action="voice"><span class="wave"><i></i><i></i><i></i><i></i></span><b>${state.listening?'停止':'说话'}</b></button></div><p>${state.listening?'正在聆听，说完后轻触停止':'按一下开始，再按一下结束'}</p></section></section></div>`}
function talkLanding(){return `<section class="talk-landing dot-matrix-landing"><div class="landing-index"><span>FIELD NOTE · 027</span><span>SHANGHAI / 31.23°N</span></div><div class="dot-stage" aria-hidden="true"><canvas id="dot-hero"></canvas><div class="dot-axis"><i></i><span>LISTENING FIELD</span><b>01</b></div></div><div class="landing-copy"><small>A QUIET PLACE FOR YOUR THOUGHTS</small><h1>今天，想从哪里<br/>开始说起？</h1><p>从一个画面、一点情绪，或者今天刚刚发生的小事开始。</p></div><div class="landing-actions"><button data-action="start-talk"><span>开始今天的对话</span><b>↗</b></button><button class="landing-mood" data-action="mood"><i>${moodIcon(state.mood)}</i><span>今日状态</span><b>${state.mood}</b></button></div></section>`}

function reportPage(){const past=reports.slice(0,2);const saved={3:{title:'第一次把经验教给别人',tag:'表达能力',index:2},12:{title:'我其实很会照顾细节',tag:'观察力',index:1},19:{title:'让杂乱重新有秩序',tag:'空间整理',index:0},27:{title:db.cards[0]?.title||'今天的成长片段',tag:db.cards[0]?'自动生成':'今日记录',index:0}};const blanks=Array.from({length:6},()=>'<i class="calendar-empty"></i>').join('');const days=Array.from({length:31},(_,i)=>{const day=i+1;const card=saved[day];return card?`<button class="calendar-day has-card card-tone-${day%3}" data-open="card-${card.index}"><time>${day}</time><img src="./src/assets/botanical-journal.png" alt="${card.title}"/><span>${card.tag}</span><b>${card.title}</b></button>`:`<div class="calendar-day"><time>${day}</time></div>`}).join('');return `<section class="daily-reel report-reel-first"><header><div><span>PAST CONVERSATION CARDS</span><h2>往日名片回顾</h2></div></header><div class="reel-window"><div class="reel-track">${past.map((r,i)=>`<article data-open="card-${i}" class="reel-card reel-${i%3}"><img src="./src/assets/botanical-journal.png" alt="${r.title}"/><div><time>${r.date}</time><small>${r.tag}</small><h3>${r.title}</h3><span>打开回顾 ↗</span></div></article>`).join('')}</div></div></section><section class="growth-calendar"><header><div><span>GROWTH CALENDAR</span><h2>2026 年 8 月</h2></div><div class="calendar-nav"><button aria-label="上个月">‹</button><b>成长月历</b><button aria-label="下个月">›</button></div></header><div class="calendar-weekdays">${['日','一','二','三','四','五','六'].map(x=>`<span>${x}</span>`).join('')}</div><div class="calendar-grid">${blanks}${days}</div></section><button class="monthly-summary-fab" data-open="full-report"><i>✦</i><span>月度总结</span><b>↗</b></button>`}

function friendPage(){return `<section class="friend-opportunity-wrap friend-section-one"><article class="social-profile-card plain-social-card"><header><span>MY SOCIAL CARD · 01</span><b>${db.profile.city||'城市未设置'} · 可线上交流</b></header><div class="social-card-main"><div class="social-card-avatar">${db.profile.name.slice(0,1)}</div><div class="social-card-identity"><h2>${db.profile.name}</h2><p>${db.profile.bio||'正在记录自己的生活经验与成长线索。'}</p></div><i class="social-card-code" aria-hidden="true">拾</i></div><div class="social-story-list social-story-two"><section><small>感兴趣</small><h3>社区分享与新手陪伴</h3><p>想认识同样关心植物和日常生活的人，一起交换真实经验。</p></section><section><small>擅长</small><h3>观察细节、分类整理、持续照护</h3><p>能从零散信息里发现差异，并整理成可以长期使用的方法。</p></section></div><footer><small>个人资料默认仅在你确认后展示</small><div><button class="social-card-primary" data-open="opportunity">查看探索方向 ↗</button><button data-open="profile-card">预览社交名片</button></div></footer></article></section><section class="friend-direction-teaser"><header><span>02 · EXPLORE DIRECTIONS</span><h2>从兴趣出发，看看可以一起做什么</h2><p>进入后会先看到感兴趣与可探索的方向；选择一个方向，再为你推荐同好的人。</p></header><button data-open="opportunity"><span>植物照护 · 社区分享 · 内容记录</span><b>打开探索方向 ↗</b></button></section><section class="friend-photo-board friend-section-three"><header><div><span>03 · LIFE MOMENTS</span><h2>从一张照片开始认识</h2></div><label><input type="file" accept="image/*" data-action="add-friend-photo"/>＋ 添加图片</label></header><div class="friend-photo-grid">${partners.map((x,i)=>`<article><div class="friend-photo-placeholder">${i===0&&state.friendPhoto?`<img src="${state.friendPhoto}" alt="刚添加的生活照片"/>`:''}<span>${['阳台植物','社区餐桌','手作时间'][i]}</span><i>${i===0&&state.friendPhoto?'':x.name[0]}</i></div><div><small>${x.role} · ${x.place}</small><h3>${x.name}</h3><p>${x.idea}</p><button data-open="partner-${i}">认识她 ↗</button></div></article>`).join('')}</div></section>`}
function mePage(){return `<section class="ability-cloudscape portrait-ability-card"><header><span>SKILL FIELD / ${skillVocabulary.length} SIGNALS</span><h2>已发现的能力线索</h2><p>能力词以泡泡浮现在云朵周围，点击任意一项即可在当前页面查看完整观察说明书。</p></header><div class="ability-sky"><div class="ability-main-cloud" aria-hidden="true"><i></i><i></i><span></span></div>${skillVocabulary.slice(0,10).map((s,i)=>`<button class="ability-bubble bubble-${i}" data-skill-modal="${i}" title="${s.evidence}"><b>${s.label}</b><span>${s.category}</span></button>`).join('')}<i class="ability-glint glint-a">✦</i><i class="ability-glint glint-b">·</i></div><footer><span>来自长期对话与行动证据</span><button data-open="vocabulary">查看全部能力词库 ↗</button></footer></section>
 <section class="settings"><button data-open="memory"><span>个人档案与记忆</span><b>23 条记录 ›</b></button><button data-open="privacy"><span>数据与摄像头权限</span><b>由你控制 ›</b></button><button data-open="export"><span>导出我的内容</span><b>›</b></button></section>`}

function moodIcon(mood){return {轻松:'❀',平静:'❋',疲惫:'❦',焦虑:'✣',开心:'✿',低落:'☁'}[mood]||'❋'}
function moodSheet(){const moods=[['轻松','今天有一点余裕'],['平静','状态稳定，可以慢慢聊'],['疲惫','希望被温柔地陪伴'],['焦虑','脑子里有很多事情'],['开心','想分享一件好事'],['低落','不想解释太多']];return `<div class="overlay" data-action="close-mood"><section class="sheet mood-sheet" onclick="event.stopPropagation()"><button class="close" data-action="close-mood">×</button><span>CHECK IN · ONLY FOR THIS TALK</span><h2>今天的你，<br/>更接近哪种状态？</h2><div>${moods.map(x=>`<button data-mood="${x[0]}" class="mood-${x[0]} ${state.mood===x[0]?'selected':''}"><i>${moodIcon(x[0])}</i><b>${x[0]}</b><span>${x[1]}</span></button>`).join('')}</div><p>这不是诊断，只用于调整这次对话的节奏和语气。</p></section></div>`}
function profileSettingsPage(){return `<section class="detail-page active profile-settings-page"><header><span>PERSONAL INFORMATION</span><h1>设置个人信息</h1><p>这些信息用于完善你的个人画像和同路人匹配，不会自动公开。</p></header><form class="profile-settings-form"><div class="profile-avatar-editor"><i>${db.profile.name.slice(0,1)}</i><div><b>${db.profile.name}</b><label>更换头像<input type="file" accept="image/*"/></label></div></div><div class="profile-form-grid"><label><span>昵称</span><input name="name" value="${db.profile.name}"/></label><label><span>生日</span><input name="birthday" type="date" value="${db.profile.birthday}"/></label><label><span>手机号码</span><input name="phone" type="tel" value="${db.profile.phone}" placeholder="用于账户安全"/></label><label><span>所在城市</span><input name="city" value="${db.profile.city}"/></label><label class="wide"><span>个人介绍</span><textarea name="bio" rows="4">${db.profile.bio}</textarea></label><label class="wide"><span>兴趣与关注方向</span><input name="interests" value="${db.profile.interests}"/><small>使用顿号分隔，例如：植物照护、社区活动、手作</small></label></div><button type="button" data-profile-save>保存个人信息</button></form></section>`}
function socialCardPage(){return `<section class="detail-page active social-card-preview-page"><header><span>SOCIAL CARD PREVIEW</span><h1>我的个人社交名片</h1><p>这是同路人看到的公开预览。手机号、生日和私人对话不会显示。</p></header><article class="social-profile-card social-profile-card-preview plain-social-card"><header><span>SHIGUANG MEMBER</span><b>${db.profile.city||'城市未设置'} · 可线上交流</b></header><div class="social-card-main"><div class="social-card-avatar">${db.profile.name.slice(0,1)}</div><div class="social-card-identity"><h2>${db.profile.name}</h2><p>${db.profile.bio}</p></div><i class="social-card-code">拾</i></div><div class="social-story-list"><section><small>正在做</small><h3>植物照护与生活记录</h3><p>持续记录阳台植物的变化，并整理容易理解的照护方法。</p></section><section><small>感兴趣</small><h3>社区分享与共同创作</h3><p>希望和认真生活的人交换经验，一起做小而真实的内容项目。</p></section><section><small>擅长</small><h3>观察、整理和耐心照护</h3><p>善于发现细节，把零散经验变成可以重复使用的方法。</p></section></div><footer><small>拾光 · 个人成长档案</small><div><button>保存图片</button><button class="social-card-primary">分享名片 ↗</button></div></footer></article></section>`}

function detailPage(type){if(type==='full-report')return fullReportPage();if(type==='profile-settings')return profileSettingsPage();if(type==='profile-card')return socialCardPage();if(type.startsWith('card-'))return cardDetailPage(Number(type.split('-')[1]));if(type.startsWith('skill-'))return skillDetailPage(Number(type.split('-')[1]));if(type.startsWith('partner-'))return partnerChatPage(Number(type.split('-')[1]));const data={
 opportunity:{eyebrow:'DIRECTION DISCOVERY · STEP 02',title:'探索感兴趣的方向',intro:'先从兴趣出发，再结合你已经表现出来的能力。选择一个方向后，系统会推荐正在做相近事情的人。',body:`<section class="direction-discovery"><article class="interest-direction"><span>我感兴趣的方向</span><h2>植物、社区与真实生活经验</h2><p>你愿意继续了解植物照护，也希望把生活中形成的方法分享给需要的人。</p><div><b>植物照护</b><b>社区分享</b><b>新手陪伴</b></div></article><section class="explorable-directions"><header><span>可探索的方向</span><h2>选择一个方向，寻找同好</h2></header>${[['01','植物照护 × 内容记录','把观察与分类经验整理成容易使用的图文内容。','最接近当前兴趣'],['02','社区植物互助','和同城伙伴交换经验，建立简单的社区养护档案。','适合线下连接'],['03','新手七日陪伴','把第一次养植物的过程做成温和、清楚的行动清单。','适合小型共创']].map(x=>`<button data-open="partners"><strong>${x[0]}</strong><div><small>${x[3]}</small><h3>${x[1]}</h3><p>${x[2]}</p></div><em>推荐同好的人 ↗</em></button>`).join('')}</section><footer class="direction-note"><span>说明</span><p>推荐依据来自双方愿意公开的兴趣、能力与合作意向，不代表合作结果。</p></footer></section>`},
 partners:{eyebrow:'PARTNER DISCOVERY',title:'寻找互补伙伴',intro:'根据真实能力证据寻找可以一起尝试小项目的人。先查看合作设想，再决定是否开始交流。',body:`<div class="partner-filters"><button class="on">最匹配</button><button>同城</button><button>可线上</button></div><div class="partner-list">${partners.map((x,i)=>`<article><div class="partner-avatar">${x.name[0]}</div><div><small>${x.role} · ${x.place}</small><h3>${x.name}</h3><p>${x.idea}</p><span>匹配依据：${x.skills.slice(0,2).join(' × ')}</span></div><b>${x.match}</b><button data-open="partner-${i}">进入伙伴空间并聊天 ↗</button></article>`).join('')}</div>`},
 memory:{eyebrow:'MEMORY & PROFILE',title:'我的手账',intro:'重要的句子、日常图像和成长证据，被整理成一本可以慢慢翻阅的私人手账。',body:`<article class="journal-cover"><img src="./src/assets/botanical-journal.png" alt="阳台植物与手写观察纸张"/><div><small>AUGUST · FIELD NOTES</small><h2>照顾，也是一种创造。</h2><p>在重复的日常里，你正在建立自己的观察方式。</p></div></article><section class="selected-lines"><span>SELECTED LINES</span><blockquote>“我想让每一盆植物，都有一个容易被理解的位置。”</blockquote><blockquote>“整理不是把东西藏起来，而是知道下一次怎么继续。”</blockquote></section><div class="memory-list">${[['08.27','你会为植物建立容易维护的分类'],['08.24','你更喜欢先观察，再决定如何行动'],['08.19','你认为家庭劳动也应该被看见'],['08.12','你曾帮助邻居理解收纳步骤']].map((x,i)=>`<article data-open="card-${Math.min(i,reports.length-1)}"><time>${x[0]}</time><p>${x[1]}</p><button data-open="card-${Math.min(i,reports.length-1)}">翻阅</button></article>`).join('')}</div>`},
 vocabulary:{eyebrow:'ABILITY LEXICON',title:'全部能力词库',intro:'每个词都必须能回到具体日记和行动证据；没有证据的词不会进入你的画像。',body:`<div class="vocabulary-grid">${skillVocabulary.map((s,i)=>`<button data-skill-modal="${i}"><span>${String(i+1).padStart(2,'0')}</span><div><b>${s.label}</b><small>${s.category} · ${s.confidence}%</small></div><em>查看证据 ↗</em></button>`).join('')}</div>`},
 privacy:{eyebrow:'DATA CONTROL',title:'数据与摄像头权限',intro:'语音、摄像头和长期记忆都必须由你主动决定。',body:`<div class="control-list"><article><div><b>语音输入</b><span>仅在按下说话后工作</span></div><button class="switch on"><i></i></button></article><article><div><b>表情辅助</b><span>${state.cameraEnabled?'本次对话已开启':'默认关闭，不保存原始视频'}</span></div><button class="switch ${state.cameraEnabled?'on':''}"><i></i></button></article><article><div><b>长期记忆</b><span>用于连接不同时间的对话</span></div><button class="switch on"><i></i></button></article><article><div><b>匿名改进</b><span>不使用你的内容训练公共模型</span></div><button class="switch"><i></i></button></article></div>`},
 export:{eyebrow:'PORTABLE ARCHIVE',title:'导出我的内容',intro:'你的对话、卡片和报告应该随时可以带走。',body:`<div class="export-options"><button><i>TXT</i><div><b>完整对话记录</b><span>按日期整理的可读文本</span></div><em>↓</em></button><button><i>PDF</i><div><b>成长卡片与报告</b><span>适合保存和打印</span></div><em>↓</em></button><button><i>JSON</i><div><b>结构化个人档案</b><span>包含记忆、能力与证据关系</span></div><em>↓</em></button></div><p class="export-note">导出只会在你的设备上生成文件，不会公开内容。</p>`}
 }[type];return `<section class="detail-page active"><header><span>${data.eyebrow}</span><h1>${data.title}</h1><p>${data.intro}</p></header>${data.body}</section>`}

function fullReportPage(){return `<section class="detail-page report-detail active"><header><span>MONTHLY REVIEW · AUGUST</span><h1>八月月度总结</h1><p>根据本月留下的对话与成长卡片，整理成一封写给你的月度回信。</p></header><article class="monthly-letter"><div class="monthly-letter-index"><span>2026</span><b>08</b><small>MONTHLY LETTER</small></div><div class="monthly-letter-body"><small>写给八月的你</small><h2>你正在从“默默完成”，走向“看见并表达自己的能力”。</h2><p>八月里，你反复谈到植物、整理和照护。过去，这些事情更像是你习惯去做的日常；现在，你开始意识到，其中包含了观察差异、建立秩序、持续照料和向别人说明方法的能力。</p><p>这个月的变化并不喧闹。你先是重新注意到生活里的小事，随后愿意为自己的选择命名，也更愿意把经验说出来。你没有突然变成另一个人，而是慢慢看见了原本就在自己身上的东西。</p><blockquote>“我做的不只是把事情完成，我也在形成自己的方法。”</blockquote><p>下个月，可以继续留意一个问题：哪些你已经熟练做到的事情，也能让另一个人少走一点弯路？不必急着证明结果，只需要把过程记录得更清楚。</p><footer><span>本月关键词</span><strong>持续照护 · 主动表达 · 连接他人</strong></footer></div></article></section>`}
function cardDetailPage(index){const r=reportItems()[index]||reports[0];return `<section class="detail-page card-detail active"><header><span>DAILY TALK · ${r.date}</span><h1>${r.title}</h1><p>这张卡片保留了当天对话中，从事件到能力线索的完整依据。</p></header><article class="journal-quote"><small>当天的你说</small><blockquote>“我没有想做一件多大的事，只是希望以后每天照顾它们的时候，更容易看懂每一盆需要什么。”</blockquote></article><section class="trace"><h2>能力是怎样被发现的</h2><ol><li><b>01</b><div><strong>发生的事情</strong><p>重新整理阳台，并为不同植物制作标签。</p></div></li><li><b>02</b><div><strong>你的选择</strong><p>先观察差异，再建立一套可以长期维护的分类。</p></div></li><li><b>03</b><div><strong>形成的线索</strong><p>${r.tag}、持续照护、把复杂信息整理清楚。</p></div></li></ol></section><button class="link-memory" data-open="memory">查看这条日记如何进入个人档案 ↗</button></section>`}
function partnerChatPage(index){const p=partners[index]||partners[0];const messages=state.partnerMessages[index]||[{role:'partner',text:p.opening}];return `<section class="detail-page partner-room active"><header><span>PARTNER SPACE · ${p.match} MATCH</span><h1>和 ${p.name} 聊聊</h1><p>${p.role} · ${p.place}</p></header><article class="partner-brief"><div class="partner-avatar">${p.name[0]}</div><div><small>共同尝试方向</small><h2>${p.idea}</h2></div><span>${p.match}</span><ul>${p.skills.map(x=>`<li>${x}</li>`).join('')}</ul><p>匹配来自双方公开的能力线索与合作意向，不代表合作结果。</p></article><section class="partner-chat" aria-label="与${p.name}的聊天"><div class="partner-chat-log">${messages.map(m=>`<article class="${m.role}"><small>${m.role==='partner'?p.name:'我'}</small><p>${m.text}</p></article>`).join('')}</div><div class="partner-composer"><textarea data-partner-input="${index}" rows="2" placeholder="介绍你想一起尝试的事情…" aria-label="给${p.name}发送消息"></textarea><button data-partner-send="${index}">发送 ↗</button></div><small>这是产品原型；消息仅保存在当前页面，不会真实发送。</small></section></section>`}
function skillDetailPage(index){const s=skillVocabulary[index]||skillVocabulary[0];const confidence=Math.round(s.confidence);const pages=[['01','AI 综合判断',`你倾向于先理解差异，再建立可以持续使用的方法。`,`这项能力反复出现在观察、分类、照护和向他人解释的过程中。你能够把零散信息转化为清楚、可执行的秩序。`],['02','典型表现','你通常怎样使用这项能力？','主动发现细微差异；建立标签、步骤或分类规则；关注方法能否长期维护；能解释自己的判断依据。'],['03','适用场景','这项能力可能在哪里继续生长？','内容与资料整理、新手指南和流程设计、社区照护与知识分享，以及需要耐心观察的协作项目。'],['04','边界与待验证','这仍是一条需要继续验证的线索。','目前证据主要来自日常生活场景，还不足以证明它在高压力、多人协作或商业项目中也会稳定发挥。']];const evidencePages=[reports[0],reports[1],reports[2],{date:'07.28',title:'为邻居说明植物养护步骤',tag:'经验表达',color:'#8fac9d'}];return `<section class="detail-page skill-detail active"><header><span>AI ABILITY DOCUMENT · UPDATED TODAY</span><h1>${s.label}能力观察说明书</h1><p>向右翻阅四张名片，查看综合判断、典型表现、适用场景和待验证边界。</p></header><section class="ability-book"><header><div><small>${s.category} · 能力线索 ${String(index+1).padStart(2,'0')}</small><b>${confidence}% 证据置信度</b></div><span>横向滑动翻页 →</span></header><div class="ability-book-pages">${pages.map((p,i)=>`<article class="ability-page-card page-${i}"><div class="page-number"><b>${p[0]}</b><span>/ 04</span></div><small>${p[1]}</small><h2>${p[2]}</h2><p>${p[3]}</p><footer><span>${s.label}</span><b>我是谁 · AI 观察</b></footer></article>`).join('')}</div><div class="book-dots">${pages.map((_,i)=>`<i class="${i===0?'on':''}"></i>`).join('')}</div></section><section class="evidence-journal evidence-book"><header><div><small>EVIDENCE BOOK</small><h2>证据索引</h2></div><span>向右翻阅 01—04 →</span></header><div class="evidence-pages">${evidencePages.map((r,i)=>`<button class="evidence-page evidence-tone-${i}" data-open="card-${Math.min(i,reports.length-1)}"><strong>${String(i+1).padStart(2,'0')}</strong><small>真实记录 · ${r.date}</small><h3>${r.title}</h3><p>${i===0?'直接支持这项能力判断，是目前关联度最高的行动记录。':'从不同生活场景补充这项能力的形成过程。'}</p><footer><span>${r.tag}</span><em>阅读原文 ↗</em></footer></button>`).join('')}</div><div class="book-dots"><i class="on"></i><i></i><i></i><i></i></div></section><section class="doc-actions"><button>这份整理准确</button><button>补充或修正</button></section></section>`}

function skillModal(index){return `<div class="skill-modal-layer" role="presentation"><section class="skill-modal-dialog" role="dialog" aria-modal="true" aria-label="能力观察说明书"><button class="skill-modal-close" aria-label="关闭能力说明书">×</button>${skillDetailPage(index)}</section></div>`}

function cameraSheet(){return `<div class="overlay" data-action="close-camera"><section class="sheet" onclick="event.stopPropagation()"><button class="close" data-action="close-camera">×</button><span>CAMERA CONSENT</span><h2>让表情成为<br/>对话的辅助线索</h2><div class="face-demo"><i></i><i></i><i></i><b>仅分析表情变化</b></div><p>摄像头不会默认开启。演示版只在设备本地显示画面；正式版需要再次确认后，才会将经过最小化处理的情绪信号交给对话模型。</p><ul><li>不用于确认你的身份</li><li>不保存原始面部视频</li><li>可以随时关闭或撤回</li></ul><button class="primary" data-action="allow-camera">理解并开启本次分析</button><button class="secondary" data-action="close-camera">暂时不用</button></section></div>`}
function workspaceSidebar(){const nav=[['talk','我的故事','⌁'],['report','我的记录','▤'],['me','我的画像','○'],['friend','我的同路人','◇']];return `<aside class="workspace-sidebar"><button class="sidebar-collapse" data-sidebar-collapse aria-label="${state.sidebarCollapsed?'展开侧边栏':'收起侧边栏'}">${state.sidebarCollapsed?'›':'‹'}</button><div class="side-brand"><i>拾</i><div><b>我是谁</b><span>GROWTH SPACE</span></div></div><nav>${nav.map(([id,label,icon])=>`<button data-tab="${id}" class="${state.tab===id&&!state.subpage?'on':''}" title="${label}"><i>${icon}</i><span>${label}</span></button>`).join('')}</nav><section class="auto-card-settings"><header><span>成长卡片</span><b>你想几点生成每日卡片？</b></header><label>每日生成时间<input type="time" value="${db.settings.dailyCardTime}" data-setting="dailyCardTime"></label><small>每天到达设定时间后，系统会整理当天对话中的重要片段、情绪与能力线索，并自动生成一张成长卡片；同一天只生成一次。</small></section><footer><button data-open="profile-settings"><span>个人信息</span><b>›</b></button><button data-open="privacy"><span>隐私与记忆</span><b>›</b></button><small>${db.profile.name} · 仅自己可见</small></footer></aside>`}
function ensureDailyCard(){const now=new Date();const day=now.toLocaleDateString('sv-SE');const [hour,minute]=(db.settings.dailyCardTime||'21:30').split(':').map(Number);const due=now.getHours()>hour||(now.getHours()===hour&&now.getMinutes()>=minute);if(!due||db.cards.some(card=>card.autoDate===day))return;const card={id:`auto-${Date.now()}`,conversationId:state.activeConversation,title:'今天的成长片段',createdAt:Date.now(),mood:state.mood,autoDate:day};db.cards.unshift(card);db.evidence.push({cardId:card.id,skills:['观察力','表达能力','自我觉察']});saveDB()}
function sidebar(){const saved=db.conversations.map((c,i)=>['今天',c.title||'新的对话',i===0?'刚刚':'稍早',c.id,c.messageCount||c.messages?.length||0]);const items=[...saved,...[['昨天','怎么把照顾经验分享出去','21:40','demo-1',6],['08.24','我是不是也有审美能力','3 天前','demo-2',5],['08.19','家庭里的工作算不算创造','1 周前','demo-3',8]]];return `<div class="drawer-layer" data-action="close-sidebar"><aside class="history-drawer" onclick="event.stopPropagation()"><header><div><span>你的对话</span><h2>历史记录</h2></div><button data-action="close-sidebar">×</button></header><button class="new-chat" data-action="new-chat">＋ 新对话</button><div class="history-list">${items.map((x,i)=>`<section><small>${x[0]}</small><button class="${state.activeConversation===x[3]?'active':''}" data-chat="${x[3]}"><div><b>${x[1]}</b><span>${x[2]} · ${x[4]} 条消息</span></div><em>›</em></button></section>`).join('')}</div><footer><div><b>${db.evidence.length+23} 条记忆</b><span>你可以随时管理或删除</span></div><button data-open="memory">管理</button></footer></aside></div>`}
function reportSheet(){return `<div class="overlay" data-action="close-report"><section class="sheet report-sheet" onclick="event.stopPropagation()"><button class="close" data-action="close-report">×</button><span>CONVERSATION CARD · 028</span><div class="card-evidence"><header><small>FROM TALK TO EVIDENCE</small><strong>一次有温度的整理</strong></header><ol><li><b>观察</b><span>发现不同植物需要不同照护</span></li><li><b>建立规则</b><span>制作标签并重新分类</span></li><li><b>形成结果</b><span>空间更容易持续维护</span></li></ol></div><h2>你今天认领的创造</h2><p>你没有简单地“收拾阳台”，而是观察、分类，并为植物建立了一套容易继续维护的秩序。</p><dl><div><dt>能力线索</dt><dd>观察力 · 分类 · 持续照护</dd></div><div><dt>新的认识</dt><dd>我能够把复杂的小事整理清楚</dd></div></dl><button class="primary" data-action="save-card">保存到个人档案</button></section></div>`}

function persistConversation(){if(!state.activeConversation)return;const c=db.conversations.find(x=>x.id===state.activeConversation);if(c){c.messages=state.messages;c.mood=state.mood;c.updatedAt=Date.now();saveDB()}}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;state.subpage=null;render()});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=e=>{e.stopPropagation();state.subpage=b.dataset.open;state.sidebar=false;render()});document.querySelectorAll('[data-chat]').forEach(b=>b.onclick=()=>{const c=db.conversations.find(x=>x.id===b.dataset.chat);state.sidebar=false;state.talkMode='conversation';state.activeConversation=b.dataset.chat;if(c){state.messages=c.messages;state.mood=c.mood||'平静'}render()});document.querySelectorAll('[data-mood]').forEach(b=>b.onclick=()=>{state.mood=b.dataset.mood;state.moodSheet=false;persistConversation();render()});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=e=>{const a=b.dataset.action;if(a==='login'){localStorage.setItem('shiguang-session','active');state.loggedIn=true;render()}if(a==='back'){state.subpage=state.subpage?.startsWith('partner-')?'partners':null;render()}if(a==='open-privacy'){state.subpage='privacy';render()}if(a==='mood'){state.moodSheet=true;render()}if(a==='close-mood'){state.moodSheet=false;render()}if(a==='sidebar'){state.sidebar=true;render()}if(a==='close-sidebar'){state.sidebar=false;render()}if(a==='new-chat'){const id=`talk-${Date.now()}`;const c={id,title:'尚未命名的新对话',mood:state.mood,createdAt:Date.now(),messages:[{role:'ai',text:'新的对话已经准备好了。今天你想先说哪一件事？'}]};db.conversations.unshift(c);saveDB();state.sidebar=false;state.activeConversation=id;state.messages=c.messages;state.talkMode='conversation';state.tab='talk';render()}if(a==='start-talk'){state.talkMode='conversation';render()}if(a==='voice'){state.listening=!state.listening;persistConversation();render()}if(a==='camera'){state.cameraSheet=true;render()}if(a==='close-camera'){state.cameraSheet=false;render()}if(a==='allow-camera'){state.cameraSheet=false;state.cameraEnabled=true;state.mood='专注';persistConversation();render()}if(a==='make-report'){persistConversation();state.report=true;render()}if(a==='close-report'){state.report=false;render()}if(a==='save-card'){const card={id:`card-${Date.now()}`,conversationId:state.activeConversation,title:'一次有温度的整理',createdAt:Date.now(),mood:state.mood};db.cards.unshift(card);db.evidence.push({cardId:card.id,skills:['观察力','分类能力','持续照护']});saveDB();state.report=false;state.tab='report';state.talkMode='conversation';render()}});document.querySelectorAll('[data-setting]').forEach(el=>el.onchange=()=>{db.settings[el.dataset.setting]=el.value;saveDB();render()});const input=document.querySelector('.composer textarea');if(input)input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&input.value.trim()){e.preventDefault();const text=input.value.trim();state.messages.push({role:'user',text},{role:'ai',text:'我记下来了。你愿意再说说，这件事里哪一个决定最像你自己吗？'});const c=db.conversations.find(x=>x.id===state.activeConversation);if(c&&c.title==='尚未命名的新对话')c.title=text.slice(0,16);persistConversation();render()}};bindPartnerChat();bindCollectors()}
function bindPartnerChat(){document.querySelectorAll('[data-partner-send]').forEach(button=>{const send=()=>{const index=Number(button.dataset.partnerSend);const input=document.querySelector(`[data-partner-input="${index}"]`);const text=input?.value.trim();if(!text)return;state.partnerMessages[index]||=[{role:'partner',text:partners[index].opening}];state.partnerMessages[index].push({role:'me',text},{role:'partner',text:'收到，很高兴认识你。这个方向和我的经验很互补，我们可以先把目标、分工和第一周的小成果写清楚。'});render()};button.onclick=send;const input=document.querySelector(`[data-partner-input="${button.dataset.partnerSend}"]`);if(input)input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}})}
function bindCollectors(){let dragged='';document.querySelectorAll('[data-skill-drag]').forEach(el=>{el.ondragstart=e=>{dragged=el.dataset.skillDrag;e.dataTransfer.setData('text/plain',dragged);el.classList.add('dragging')};el.ondragend=()=>el.classList.remove('dragging')});const box=document.querySelector('[data-dropbox]');if(box){box.ondragover=e=>{e.preventDefault();box.classList.add('ready')};box.ondragleave=()=>box.classList.remove('ready');box.ondrop=e=>{e.preventDefault();const word=e.dataTransfer.getData('text/plain')||dragged;if(word&&!db.collected.includes(word)){db.collected.push(word);saveDB()}render()}}const file=document.querySelector('[data-action="add-photo"]');if(file)file.onchange=()=>{if(file.files?.[0]){db.cards.unshift({id:`photo-${Date.now()}`,title:'今天添加的一张照片',createdAt:Date.now(),mood:state.mood});saveDB();render()}};document.querySelectorAll('[data-action="add-friend-photo"]').forEach(input=>input.onchange=()=>{const image=input.files?.[0];if(!image)return;const reader=new FileReader();reader.onload=()=>{state.friendPhoto=reader.result;render()};reader.readAsDataURL(image)});initDotHero()}

function initDotHero(){
 const canvas=document.querySelector('#dot-hero');if(!canvas)return;
 const ctx=canvas.getContext('2d');const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 let w=0,h=0,dpr=1,points=[],pointer={x:-999,y:-999,active:false};
 const resize=()=>{const r=canvas.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);w=r.width;h=r.height;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);points=[];
  const gap=w<390?8:9,cx=w*.57,cy=h*.47,maxR=Math.min(w,h)*.43;
  for(let y=7;y<h;y+=gap)for(let x=7;x<w;x+=gap){const dx=x-cx,dy=y-cy;const r=Math.hypot(dx,dy),a=Math.atan2(dy,dx);const edge=maxR*(.66+.15*Math.cos(a*5)+.055*Math.cos(a*10));const field=Math.sin(x*.045)+Math.cos(y*.038);if(r<edge+field*5||Math.random()<.025*Math.max(0,1-r/maxR))points.push({x,y,seed:Math.random()*6.28,size:.65+Math.random()*1.45,depth:Math.max(0,1-r/maxR)});}
 };
 const locate=e=>{const r=canvas.getBoundingClientRect(),p=e.touches?.[0]||e;pointer.x=p.clientX-r.left;pointer.y=p.clientY-r.top;pointer.active=true};
 canvas.addEventListener('pointermove',locate);canvas.addEventListener('pointerleave',()=>pointer.active=false);canvas.addEventListener('touchmove',locate,{passive:true});
 resize();new ResizeObserver(resize).observe(canvas);
 const draw=now=>{if(!canvas.isConnected)return;ctx.clearRect(0,0,w,h);const t=now*.001;
  for(const p of points){let x=p.x+Math.sin(t*.7+p.y*.035+p.seed)*2.4,y=p.y+Math.cos(t*.55+p.x*.028+p.seed)*2;let force=0;if(pointer.active){const dx=x-pointer.x,dy=y-pointer.y,dist=Math.hypot(dx,dy);if(dist<92){force=(92-dist)/92;x+=dx/(dist||1)*force*18;y+=dy/(dist||1)*force*18;}}
   const pulse=.78+.22*Math.sin(t*1.1+p.seed);ctx.beginPath();ctx.arc(x,y,p.size*(.72+p.depth*.55+force*.32)*pulse,0,Math.PI*2);ctx.fillStyle=`rgba(29,76,151,${.24+p.depth*.66})`;ctx.fill();
  }
  if(!reduced)requestAnimationFrame(draw);
 };requestAnimationFrame(draw);
}
async function boot(){const token=localStorage.getItem('shiguang-token');if(token){try{await apiRequest('/api/v1/auth/session');const profile=await hydrateAccount();state.loggedIn=true;state.profileSetup=!profile.onboardingComplete}catch{localStorage.removeItem('shiguang-token')}}render()}
boot();
